### ISSUE TITLE
Unsafe undefined check

### ISSUE THREAD

**Issue by shnhrrsn** [MaxMEllon/babel-plugin-transform-isNil#4]
Code currently expands to `var === undefined` which isn’t safe in the browser as `undefined` can be changed: http://www.2ality.com/2013/04/check-undefined.html

The undefined check should probably expand to `typeof var === 'undefined'` or `var === void 0`

**Comment by MaxMEllon** [comment]
hmmm...

I consider to use `void 0`.

Thanks you report !

**Comment by MaxMEllon** [comment]
Sorry for the late reply
