### ISSUE TITLE
Why not cache the result of functions?

### ISSUE THREAD

**Issue by carcinocron** [MaxMEllon/babel-plugin-transform-isNil#7]
For this example:

In

```
if (hoge.poge(hoge).isNil) {
  console.log('returned value of hoge.poge() function is null or undefined');
}
```

Out

```
if (hoge.poge(hoge) === null || hoge.poge(hoge) === undefined) {
  console.log('returned value of hoge.poge() function is null or undefined');
}
```

Wouldn't it be better to transform to:

```
var _tmpVar = hoge.poge(hoge);
if (_tmpVar === null || _tmpVar === undefined) {
  console.log('returned value of hoge.poge() function is null or undefined');
}
```

`poge()` could have side effects resulting in different output the second call or affecting the rest of the program. I suspect that this would be faster, too.

**Comment by MaxMEllon** [comment]
Thanks for the advice.
I'm not sure if I can do that yet. I'll try Anyway
Could you send me PR if it is ok?

**Comment by carcinocron** [comment]
I'm not if I can do a PR at this time but one more thing: I think `_tmpVar === undefined` is invalid, should probably use instead `typeof _tmpVar === "undefined"`

http://stackoverflow.com/questions/4725603/variable-undefined-vs-typeof-variable-undefined

**Comment by MaxMEllon** [comment]
What do you think to do this?

``` js
if (hoge.poge(args) == null) { }
```

`== null` means `=== null || === undefined` the same.
but I think it can not be said that beautiful.

**Comment by carcinocron** [comment]
I think that is not going to work.

technically, somebody can define undefined, so you should always use `typeof x === 'undefined'`.

```
// this can break code that relies on undefined being undefined
var undefined = 'defined';
```

Typeof will need to be first:

```
>>> asdfsdfds === null
Uncaught ReferenceError: asdfsdfds is not defined(…)(anonymous function)
>>> (asdfsdfds === null || typeof asdfsdfds === 'undefined')
Uncaught ReferenceError: asdfsdfds is not defined(…)
>>> (typeof asdfsdfds === 'undefined' || asdfsdfds === null)
true
```

It looks like you still need `typeof _tmpVar === 'undefined' || _tmpVar === null` because a function can return both null and undefined.

```
>>> function a(){ return null;}; function b(){}; [a(),b()];
[null, undefined]
```

Javascript is weird in that it has 2 types of "non-values": http://www.2ality.com/2013/04/quirk-undefined.html Most languages have only 1.

**Comment by MaxMEllon** [comment]
Of the `undefined` can be defined by the user is limited to older versions of the engine.
Babel is inserted in the automatic `use strict`.
so, I think may not use `typeof x === 'undefined'`.

In Chrome 53.0.2785.143

```
> undefined = 'defined'
< "defined"
> undefined
< undefined
```

**Comment by MaxMEllon** [comment]
https://github.com/MaxMEllon/babel-plugin-transform-isNil/commit/bf062919bc5aa226db704d3abbf1096b12ce5af0

Just fixed.
cached value and  compare by`typeof  x === 'undefined'`.
